name: CI

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch: {}

jobs:
  lint:
    name: Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('test1/**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dev dependencies
        run: |
          cd test1
          python -m pip install --upgrade pip
          pip install -e '.[dev]'

      - name: Run ruff
        run: |
          cd test1
          ruff check .

  typecheck:
    name: Mypy Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('test1/**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dev dependencies
        run: |
          cd test1
          python -m pip install --upgrade pip
          pip install -e '.[dev]'

      - name: Run mypy
        run: |
          cd test1
          mypy src tests

  test:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('test1/**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dev dependencies
        run: |
          cd test1
          python -m pip install --upgrade pip
          pip install -e '.[dev]'

      - name: Run tests
        run: |
          cd test1
          pytest -q

  terraform:
    name: Terraform validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform init & validate
        run: |
          cd test1/terraform
          terraform init -input=false
          terraform validate

  ai-tests:
    name: AI tests (optional, heavy)
    runs-on: ubuntu-latest
    # Run only manually or on pushes to main to avoid slowing PRs by default
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('test1/**/pyproject.toml') }}-ai
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dev + ai extras (heavy)
        run: |
          cd test1
          python -m pip install --upgrade pip
          pip install -e '.[dev,ai]'

      - name: Run AI tests
        run: |
          cd test1
          pytest -q tests/test_ai.py
