repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.256
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        additional_dependencies: ["mypy==1.9"]
        args: ["--config-file", "mypy.ini"]
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        additional_dependencies: ["pydocstyle==6.3.0"]
        args: ["--convention=google"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.4.1
    hooks:
      - id: prettier
        files: "\.(md|pyproject\.toml|yaml|yml)$"
