name: Auto Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [ main, master ]

jobs:
  checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'

      - name: Run lint via uv
        id: ruff
        continue-on-error: true
        run: |
          uv lint --fix || true

      - name: Report ruff via reviewdog
        if: github.event_name == 'pull_request'
        uses: reviewdog/action-ruff@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
          filter_mode: added

      - name: Run typecheck via uv
        id: mypy
        continue-on-error: true
        run: |
          uv typecheck || true

      - name: Report mypy via reviewdog
        if: github.event_name == 'pull_request'
        uses: reviewdog/action-mypy@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
          filter_mode: added

      - name: Run pytest (junit xml) via uv
        id: pytest
        continue-on-error: true
        run: |
          uv test --junitxml=pytest-report.xml || true

      - name: Report pytest via reviewdog
        if: github.event_name == 'pull_request'
        uses: reviewdog/action-pytest@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
          filter_mode: added

      - name: Upload pytest report
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: pytest-report
            path: pytest-report.xml

      - name: Upload CodeQL SARIF (if present)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: codeql-sarif
          path: codeql-results.sarif

      - name: Post PR summary comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const ruffStatus = "${{ steps.ruff.outcome }}";
            const mypyStatus = "${{ steps.mypy.outcome }}";
            const pytestStatus = "${{ steps.pytest.outcome }}";
            const body = `### Automated code review results\n\n- ruff: ${ruffStatus}\n- mypy: ${mypyStatus}\n- pytest: ${pytestStatus}\n\nArtifacts: pytest-report.xml (attached).`;
            const pr = context.payload.pull_request.number;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr,
              body,
            });
